function chart_data(){
    var chart_data = 
        [
  {
    "Name Eng": "He Xiangjian",
    "Name CN": "何享健",
    "Total Amount (million Yuan)": 400,
    "From Province": "Guangdong",
    "Age": 73,
    "Generosity": "1.00%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 400,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Jianlin",
    "Name CN": "王健林",
    "Total Amount (million Yuan)": 315,
    "From Province": "Beijing",
    "Age": 60,
    "Generosity": "0.29%",
    "Industry": "Real Estate",
    "Education": 100,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 210,
    "Disaster Relief": 5,
    "Culture": 0
  },
  {
    "Name Eng": "Tang Lixin",
    "Name CN": "唐立新",
    "Total Amount (million Yuan)": 315,
    "From Province": "Sichuan",
    "Age": 52,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 315,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Xing Fuping",
    "Name CN": "邢福平",
    "Total Amount (million Yuan)": 310,
    "From Province": "Jilin",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 310,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Yusuo",
    "Name CN": "王玉锁",
    "Total Amount (million Yuan)": 303,
    "From Province": "Hebei",
    "Age": 51,
    "Generosity": "2.59%",
    "Industry": "Energy",
    "Education": 301,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 2,
    "Culture": 0
  },
  {
    "Name Eng": "Xu Lianjie",
    "Name CN": "许连捷",
    "Total Amount (million Yuan)": 279,
    "From Province": "Fujian",
    "Age": 62,
    "Generosity": "1.91%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 279,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lu Chaokang",
    "Name CN": "卢朝康",
    "Total Amount (million Yuan)": 220,
    "From Province": "Chongqing",
    "Age": 54,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 220,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lu Zhiqiang",
    "Name CN": "卢志强",
    "Total Amount (million Yuan)": 150,
    "From Province": "Beijing",
    "Age": 63,
    "Generosity": "0.46%",
    "Industry": "Real Estate",
    "Education": 150,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wu Shaoxun",
    "Name CN": "吴少勋",
    "Total Amount (million Yuan)": 126,
    "From Province": "Hubei",
    "Age": 59,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 26,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 100,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhou Hansheng",
    "Name CN": "周汉生",
    "Total Amount (million Yuan)": 112,
    "From Province": "Hubei",
    "Age": 52,
    "Generosity": 0,
    "Industry": "Tech/IT",
    "Education": 112,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yang Huiyan",
    "Name CN": "杨惠妍",
    "Total Amount (million Yuan)": 102,
    "From Province": "Guangdong",
    "Age": 34,
    "Generosity": "0.35%",
    "Industry": "Real Estate",
    "Education": 102,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Miaotong",
    "Name CN": "王苗通",
    "Total Amount (million Yuan)": 101,
    "From Province": "Zhejiang",
    "Age": 58,
    "Generosity": "5.61%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 101,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Jack Ma Yun",
    "Name CN": "马云",
    "Total Amount (million Yuan)": 100,
    "From Province": "Zhejiang",
    "Age": 51,
    "Generosity": "0.10%",
    "Industry": "Tech/IT",
    "Education": 100,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ma Huateng",
    "Name CN": "马化腾",
    "Total Amount (million Yuan)": 100,
    "From Province": "Guangdong",
    "Age": 44,
    "Generosity": "0.12%",
    "Industry": "Tech/IT",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 100,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Guo Guangchang",
    "Name CN": "郭广昌",
    "Total Amount (million Yuan)": 100,
    "From Province": "Shanghai",
    "Age": 48,
    "Generosity": "0.22%",
    "Industry": "Finance",
    "Education": 100,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Defu",
    "Name CN": "李德福",
    "Total Amount (million Yuan)": 100,
    "From Province": "Tianjin",
    "Age": 57,
    "Generosity": "2.76%",
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 100,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Chichang",
    "Name CN": "陈炽昌",
    "Total Amount (million Yuan)": 100,
    "From Province": "Guangdong",
    "Age": 44,
    "Generosity": "5.36%",
    "Industry": "Education",
    "Education": 100,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Jingruo",
    "Name CN": "张敬若",
    "Total Amount (million Yuan)": 100,
    "From Province": "Hunan",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 100,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Xue Xingyuan",
    "Name CN": "薛行远",
    "Total Amount (million Yuan)": 82,
    "From Province": "Fujian",
    "Age": 53,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 80,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 2
  },
  {
    "Name Eng": "Dai Jianliang",
    "Name CN": "戴建良",
    "Total Amount (million Yuan)": 70,
    "From Province": "Guizhou",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 70,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Liu Shui",
    "Name CN": "刘水",
    "Total Amount (million Yuan)": 68,
    "From Province": "Guangdong",
    "Age": 46,
    "Generosity": "1.80%",
    "Industry": "Real Estate",
    "Education": 67,
    "Environment": 1,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Xin",
    "Name CN": "张欣",
    "Total Amount (million Yuan)": 62,
    "From Province": "Beijing",
    "Age": 50,
    "Generosity": "0.43%",
    "Industry": "Real Estate",
    "Education": 62,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhu Gongshan",
    "Name CN": "朱共山",
    "Total Amount (million Yuan)": 60,
    "From Province": "Shanghai",
    "Age": 57,
    "Generosity": "0.81%",
    "Industry": "Energy",
    "Education": 60,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Dayan",
    "Name CN": "李大彦",
    "Total Amount (million Yuan)": 56,
    "From Province": "Beijing",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 6,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 50,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Liang Guangwei",
    "Name CN": "梁光伟",
    "Total Amount (million Yuan)": 55,
    "From Province": "Guangdong",
    "Age": 52,
    "Generosity": "2.50%",
    "Industry": "Real Estate",
    "Education": 5,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 50,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Shu Yuhui",
    "Name CN": "束昱辉",
    "Total Amount (million Yuan)": 53,
    "From Province": "Tianjin",
    "Age": 47,
    "Generosity": 0,
    "Industry": "Healthcare",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 50,
    "Social Welfare": 3,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lou Yongliang",
    "Name CN": "楼永良",
    "Total Amount (million Yuan)": 53,
    "From Province": "Zhejiang",
    "Age": 61,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 1,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 51,
    "Disaster Relief": 1,
    "Culture": 0
  },
  {
    "Name Eng": "Dang Yanbao",
    "Name CN": "党彦宝",
    "Total Amount (million Yuan)": 51,
    "From Province": "Gansu",
    "Age": 42,
    "Generosity": 0,
    "Industry": "Energy",
    "Education": 51,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Xianyi",
    "Name CN": "李贤义",
    "Total Amount (million Yuan)": 51,
    "From Province": "Guangdong",
    "Age": 63,
    "Generosity": "2.27%",
    "Industry": "Manufacturing",
    "Education": 1,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 50,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Jinyuan",
    "Name CN": "李金元",
    "Total Amount (million Yuan)": 50,
    "From Province": "Tianjin",
    "Age": 57,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 1,
    "Social Welfare": 1,
    "Disaster Relief": 49,
    "Culture": 0
  },
  {
    "Name Eng": "Jiang Rensheng",
    "Name CN": "蒋仁生",
    "Total Amount (million Yuan)": 50,
    "From Province": "Chongqing",
    "Age": 62,
    "Generosity": "0.58%",
    "Industry": "Healthcare",
    "Education": 50,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Xu Hang",
    "Name CN": "徐航",
    "Total Amount (million Yuan)": 50,
    "From Province": "Guangdong",
    "Age": 53,
    "Generosity": "2.01%",
    "Industry": "Manufacturing",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 20,
    "Social Welfare": 20,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Wei",
    "Name CN": "王卫",
    "Total Amount (million Yuan)": 38,
    "From Province": "Guangdong",
    "Age": 44,
    "Generosity": 0,
    "Industry": "Transportation",
    "Education": 5,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 33,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zheng Dong",
    "Name CN": "郑东",
    "Total Amount (million Yuan)": 50,
    "From Province": "Beijing",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Other",
    "Education": 50,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhou Xijian",
    "Name CN": "周希俭",
    "Total Amount (million Yuan)": 50,
    "From Province": "Jiangsu",
    "Age": 40,
    "Generosity": 0,
    "Industry": "Finance",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 50,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Dongsheng",
    "Name CN": "陈东升",
    "Total Amount (million Yuan)": 50,
    "From Province": "Beijing",
    "Age": 58,
    "Generosity": 0,
    "Industry": "Finance",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 50
  },
  {
    "Name Eng": "Yan Zhi",
    "Name CN": "阎志",
    "Total Amount (million Yuan)": 50,
    "From Province": "Hubei",
    "Age": 43,
    "Generosity": "0.74%",
    "Industry": "Real Estate",
    "Education": 50,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Cheng Lianying",
    "Name CN": "程连英",
    "Total Amount (million Yuan)": 40,
    "From Province": "Hubei",
    "Age": 48,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 40,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  
  {
    "Name Eng": "Shi Shiqi",
    "Name CN": "史世奇",
    "Total Amount (million Yuan)": 36,
    "From Province": "N.A.",
    "Age": 74,
    "Generosity": 0,
    "Industry": "Other",
    "Education": 36,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Feng",
    "Name CN": "陈峰",
    "Total Amount (million Yuan)": 31,
    "From Province": "Hainan",
    "Age": 62,
    "Generosity": 0,
    "Industry": "Transportation",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 6,
    "Culture": 0
  },
  {
    "Name Eng": "Deng Wei",
    "Name CN": "邓伟",
    "Total Amount (million Yuan)": 31,
    "From Province": "Beijing",
    "Age": 52,
    "Generosity": "2.59%",
    "Industry": "Tech/IT",
    "Education": 31,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ke Xiping",
    "Name CN": "柯希平",
    "Total Amount (million Yuan)": 31,
    "From Province": "Fujian",
    "Age": 55,
    "Generosity": "4.23%",
    "Industry": "Real Estate",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 11,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lin Tengjiao",
    "Name CN": "林腾蛟",
    "Total Amount (million Yuan)": 30,
    "From Province": "Fujian",
    "Age": 47,
    "Generosity": "0.44%",
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 30
  },
  {
    "Name Eng": "Yuan Yanming",
    "Name CN": "袁艳明",
    "Total Amount (million Yuan)": 30,
    "From Province": "Sichuan",
    "Age": 55,
    "Generosity": 0,
    "Industry": "Tech/IT",
    "Education": 30,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Mao Lixiang",
    "Name CN": "茅理翔",
    "Total Amount (million Yuan)": 30,
    "From Province": "Zhejiang",
    "Age": 74,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 30,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Sun Yinhuan",
    "Name CN": "孙荫环",
    "Total Amount (million Yuan)": 28,
    "From Province": "Liaoning",
    "Age": 66,
    "Generosity": "0.80%",
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 25,
    "Disaster Relief": 3,
    "Culture": 0
  },
  {
    "Name Eng": "Shao Genhuo",
    "Name CN": "邵根伙",
    "Total Amount (million Yuan)": 25,
    "From Province": "Beijing",
    "Age": 50,
    "Generosity": "0.38%",
    "Industry": "Tech/IT",
    "Education": 15,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Xu Jiayin",
    "Name CN": "许家印",
    "Total Amount (million Yuan)": 21,
    "From Province": "Guangdong",
    "Age": 57,
    "Generosity": "0.09%",
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 21,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Tian",
    "Name CN": "王填",
    "Total Amount (million Yuan)": 20,
    "From Province": "Guangdong",
    "Age": 47,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 20,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Xue Zhongxing",
    "Name CN": "薛中行",
    "Total Amount (million Yuan)": 20,
    "From Province": "Shanghai",
    "Age": 41,
    "Generosity": 0,
    "Industry": "Finance",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Yidan",
    "Name CN": "陈一丹",
    "Total Amount (million Yuan)": 20,
    "From Province": "Guangdong",
    "Age": 44,
    "Generosity": 0,
    "Industry": "Tech/IT",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Nan Cunhui",
    "Name CN": "南存辉",
    "Total Amount (million Yuan)": 20,
    "From Province": "Zhejiang",
    "Age": 52,
    "Generosity": "0.35%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 20,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Ke",
    "Name CN": "陈柯",
    "Total Amount (million Yuan)": 20,
    "From Province": "Sichuan",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Tech/IT",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Liao Xin",
    "Name CN": "廖昕",
    "Total Amount (million Yuan)": 20,
    "From Province": "Sichuan",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Tech/IT",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Feng Weimin",
    "Name CN": "冯为民",
    "Total Amount (million Yuan)": 20,
    "From Province": "Beijing",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Finance",
    "Education": 20,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Ailian",
    "Name CN": "陈爱莲",
    "Total Amount (million Yuan)": 18,
    "From Province": "Zhejiang",
    "Age": 57,
    "Generosity": "0.88%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 10,
    "Healthcare": 0,
    "Social Welfare": 8,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhou Fangjie",
    "Name CN": "周方洁",
    "Total Amount (million Yuan)": 15,
    "From Province": "Zhejiang",
    "Age": 51,
    "Generosity": "3.31%",
    "Industry": "Tech/IT",
    "Education": 15,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yu Lirong",
    "Name CN": "于立荣",
    "Total Amount (million Yuan)": 14,
    "From Province": "Beijing",
    "Age": 40,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 13,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 1,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zong Qinghou",
    "Name CN": "宗庆后",
    "Total Amount (million Yuan)": 13,
    "From Province": "Zhejiang",
    "Age": 70,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 2,
    "Social Welfare": 1,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhou Xuzhou",
    "Name CN": "周旭洲",
    "Total Amount (million Yuan)": 13,
    "From Province": "Anhui",
    "Age": 0,
    "Generosity": "5.56%",
    "Industry": "Real Estate",
    "Education": 13,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lin Weiguang",
    "Name CN": "林伟光",
    "Total Amount (million Yuan)": 13,
    "From Province": "Guangdong",
    "Age": 52,
    "Generosity": "0.83%",
    "Industry": "Energy",
    "Education": 13,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Huang Hongyun",
    "Name CN": "黄红云",
    "Total Amount (million Yuan)": 11,
    "From Province": "Chongqing",
    "Age": 49,
    "Generosity": "0.39%",
    "Industry": "Real Estate",
    "Education": 3,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 8,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yao Zhenhua",
    "Name CN": "姚振华",
    "Total Amount (million Yuan)": 11,
    "From Province": "Guangdong",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 11,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Jianyi",
    "Name CN": "王建沂",
    "Total Amount (million Yuan)": 11,
    "From Province": "Zhejiang",
    "Age": 52,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 1,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Shiping",
    "Name CN": "张士平",
    "Total Amount (million Yuan)": 10,
    "From Province": "Shandong",
    "Age": 69,
    "Generosity": "0.02%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Feng Xijian",
    "Name CN": "冯西见",
    "Total Amount (million Yuan)": 10,
    "From Province": "Shaanxi",
    "Age": 48,
    "Generosity": 0,
    "Industry": "Transportation",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Hongdao",
    "Name CN": "陈鸿道",
    "Total Amount (million Yuan)": 10,
    "From Province": "Guangdong",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhao Junyi",
    "Name CN": "赵军屹",
    "Total Amount (million Yuan)": 10,
    "From Province": "Tianjin",
    "Age": 46,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Guangzhong",
    "Name CN": "李光忠",
    "Total Amount (million Yuan)": 10,
    "From Province": "Shanxi",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Li Jie",
    "Name CN": "李杰",
    "Total Amount (million Yuan)": 10,
    "From Province": "Hubei",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Healthcare",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Niu Gang",
    "Name CN": "牛钢",
    "Total Amount (million Yuan)": 10,
    "From Province": "Liaoning",
    "Age": 56,
    "Generosity": "0.82%",
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 10,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "You Zhisheng",
    "Name CN": "游志胜",
    "Total Amount (million Yuan)": 10,
    "From Province": "Sichuan",
    "Age": 70,
    "Generosity": "2.39%",
    "Industry": "Tech/IT",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Yin",
    "Name CN": "张茵",
    "Total Amount (million Yuan)": 10,
    "From Province": "Guangdong",
    "Age": 58,
    "Generosity": "0.06%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lu Guangxiu",
    "Name CN": "卢光琇",
    "Total Amount (million Yuan)": 10,
    "From Province": "N.A.",
    "Age": 76,
    "Generosity": 0,
    "Industry": "Healthcare",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhao Chunhua",
    "Name CN": "赵春华",
    "Total Amount (million Yuan)": 10,
    "From Province": "Hubei",
    "Age": 57,
    "Generosity": 0,
    "Industry": "Healthcare",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Liu Qiangdong",
    "Name CN": "刘强东",
    "Total Amount (million Yuan)": 10,
    "From Province": "Beijing",
    "Age": 41,
    "Generosity": "0.02%",
    "Industry": "Tech/IT",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yu Bin",
    "Name CN": "余斌",
    "Total Amount (million Yuan)": 10,
    "From Province": "Guangdong",
    "Age": 50,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 10,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yang Yuanqing",
    "Name CN": "杨元庆",
    "Total Amount (million Yuan)": 10,
    "From Province": "Beijing",
    "Age": 51,
    "Generosity": "0.18%",
    "Industry": "Tech/IT",
    "Education": 10,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Shen Xiaoping",
    "Name CN": "沈小平",
    "Total Amount (million Yuan)": 9,
    "From Province": "Jiangsu",
    "Age": 52,
    "Generosity": "0.68%",
    "Industry": "Manufacturing",
    "Education": 6,
    "Environment": 0,
    "Healthcare": 3,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Jindong",
    "Name CN": "张近东",
    "Total Amount (million Yuan)": 9,
    "From Province": "Jiangsu",
    "Age": 52,
    "Generosity": "0.04%",
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 4,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Cui Genliang",
    "Name CN": "崔根良",
    "Total Amount (million Yuan)": 8,
    "From Province": "Jiangsu",
    "Age": 57,
    "Generosity": "0.30%",
    "Industry": "Manufacturing",
    "Education": 1,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 2
  },
  {
    "Name Eng": "Xu Shihui",
    "Name CN": "许世辉",
    "Total Amount (million Yuan)": 8,
    "From Province": "Fujian",
    "Age": 57,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 8,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ye Huaneng",
    "Name CN": "叶华能",
    "Total Amount (million Yuan)": 7,
    "From Province": "Guangdong",
    "Age": 64,
    "Generosity": "0.24%",
    "Industry": "Energy",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 2,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Jinshi",
    "Name CN": "陈锦石",
    "Total Amount (million Yuan)": 6,
    "From Province": "Jiangsu",
    "Age": 53,
    "Generosity": "0.11%",
    "Industry": "Real Estate",
    "Education": 1,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wang Zhentao",
    "Name CN": "王振滔",
    "Total Amount (million Yuan)": 6,
    "From Province": "Zhejiang",
    "Age": 50,
    "Generosity": "0.16%",
    "Industry": "Consumer",
    "Education": 6,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ren Yuanlin",
    "Name CN": "任元林",
    "Total Amount (million Yuan)": 5,
    "From Province": "Jiangsu",
    "Age": 62,
    "Generosity": "0.09%",
    "Industry": "Manufacturing",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Wu Yajun",
    "Name CN": "吴亚军",
    "Total Amount (million Yuan)": 5,
    "From Province": "Beijing",
    "Age": 51,
    "Generosity": "0.02%",
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Chen Kaixuan",
    "Name CN": "陈凯旋",
    "Total Amount (million Yuan)": 5,
    "From Province": "Guangdong",
    "Age": 58,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Luo Yong",
    "Name CN": "罗勇",
    "Total Amount (million Yuan)": 5,
    "From Province": "Sichuan",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 5,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Cen Zhaoxiong",
    "Name CN": "岑兆雄",
    "Total Amount (million Yuan)": 4,
    "From Province": "Guangdong",
    "Age": 45,
    "Generosity": "0.12%",
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 4,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Lu Fuming",
    "Name CN": "卢福明",
    "Total Amount (million Yuan)": 4,
    "From Province": "Henan",
    "Age": 57,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 4,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ma Xingtian",
    "Name CN": "马兴田",
    "Total Amount (million Yuan)": 4,
    "From Province": "Guangdong",
    "Age": 46,
    "Generosity": "0.07%",
    "Industry": "Healthcare",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 4,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yang Zhuoshu",
    "Name CN": "杨卓舒",
    "Total Amount (million Yuan)": 3,
    "From Province": "Hebei",
    "Age": 63,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 2,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 1,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Rongming",
    "Name CN": "张荣明",
    "Total Amount (million Yuan)": 3,
    "From Province": "Beijing",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Consumer",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 3,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Zhang Rugeng",
    "Name CN": "章如庚",
    "Total Amount (million Yuan)": 3,
    "From Province": "Zhejiang",
    "Age": 59,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 3,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Ou Zongrong",
    "Name CN": "欧宗荣",
    "Total Amount (million Yuan)": 2,
    "From Province": "Fujian",
    "Age": 51,
    "Generosity": 0,
    "Industry": "Real Estate",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 2,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yan Xijun",
    "Name CN": "闫希军",
    "Total Amount (million Yuan)": 2,
    "From Province": "Tianjin",
    "Age": 62,
    "Generosity": 0,
    "Industry": "Healthcare",
    "Education": 0,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 2,
    "Culture": 0
  },
  {
    "Name Eng": "Li Hejun",
    "Name CN": "李河君",
    "Total Amount (million Yuan)": 1,
    "From Province": "Beijing",
    "Age": 48,
    "Generosity": "0.00%",
    "Industry": "Energy",
    "Education": 0,
    "Environment": 1,//1000,
    "Healthcare": 0,
    "Social Welfare": 1,
    "Disaster Relief": 0,
    "Culture": 0
  },
  {
    "Name Eng": "Yu Sihai",
    "Name CN": "喻四海",
    "Total Amount (million Yuan)": 1,
    "From Province": "Jiangsu",
    "Age": 0,
    "Generosity": 0,
    "Industry": "Manufacturing",
    "Education": 1,
    "Environment": 0,
    "Healthcare": 0,
    "Social Welfare": 0,
    "Disaster Relief": 0,
    "Culture": 0
  }
]
    return chart_data;    
}

function chart_month_data(){

    var chart_month_data = 
    [
      {
        "Month": "Sep 14",
        "Amount": 393
      },
      {
        "Month": "Oct 14",
        "Amount": 1402
      },
      {
        "Month": "Nov 14",
        "Amount": 250
      },
      {
        "Month": "Dec 14",
        "Amount": 966
      },
      {
        "Month": "Jan 15",
        "Amount": 107
      },
      {
        "Month": "Feb 15",
        "Amount": 43
      },
      {
        "Month": "Mar 15",
        "Amount": 157
      },
      {
        "Month": "Apr 15",
        "Amount": 380
      },
      {
        "Month": "May 15",
        "Amount": 335
      },
      {
        "Month": "Jun 15",
        "Amount": 428
      },
      {
        "Month": "Jul 15",
        "Amount": 574
      },
      {
        "Month": "Aug 15",
        "Amount": 111
      }
    ];
    return chart_month_data;
}

function map_chart_data(){
    var map_chart_data = [
  {
    "Province": "Anhui",
    "Total amount received": 0,
    "Total giving amount": 1,
    "Philanthropists": 1,
    "Leader": "Zhou Xuzhou",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 1,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Beijing",
    "Total amount received": 920.13,
    "Total giving amount": 791.68,
    "Philanthropists": 15,
    "Leader": "Wang Jianlin",
    "Beijing": 124.1,
    "Chongqing": 5,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 200,
    "Hebei": 0,
    "Heilongjiang": 12,
    "Henan": 0,
    "Hubei": 50,
    "Hunan": 0,
    "Jiangsu": 1,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 10,
    "Multiple Locations": 0,
    "Nepal": 5,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 160,
    "Shanxi": 0,
    "Sichuan": 100,
    "Tianjin": 50,
    "Tibet": 0,
    "US": 62,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 10
  },
  {
    "Province": "Chongqing",
    "Total amount received": 565.6,
    "Total giving amount": 280.6,
    "Philanthropists": 3,
    "Leader": "Lu Chaokang",
    "Beijing": 0,
    "Chongqing": 230.6,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 50,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Fujian",
    "Total amount received": 348.17,
    "Total giving amount": 430.77,
    "Philanthropists": 6,
    "Leader": "Xu Lianjie",
    "Beijing": 80,
    "Chongqing": 0,
    "Fujian": 348.17,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 2,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0.6,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Gansu",
    "Total amount received": 26,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Guangdong",
    "Total amount received": 820.8,
    "Total giving amount": 1098.83,
    "Philanthropists": 21,
    "Leader": "He Xiangjian",
    "Beijing": 163.03,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 820.8,
    "Guangxi": 10,
    "Guizhou": 5,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 20,
    "Hunan": 33,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 10,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 20,
    "Zhejiang": 0
  },
  {
    "Province": "Guangxi",
    "Total amount received": 60,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Guizhou",
    "Total amount received": 275,
    "Total giving amount": 70,
    "Philanthropists": 1,
    "Leader": "Dai Jianliang",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 70,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Hainan",
    "Total amount received": 0,
    "Total giving amount": 31,
    "Philanthropists": 1,
    "Leader": "Chen Feng",
    "Beijing": 5,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 6,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 20,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Hebei",
    "Total amount received": 0.5,
    "Total giving amount": 305.4,
    "Philanthropists": 2,
    "Leader": "Wang Yusuo",
    "Beijing": 302,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0.5,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0.9,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 2,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Heilongjiang",
    "Total amount received": 12,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Henan",
    "Total amount received": 4,
    "Total giving amount": 4,
    "Philanthropists": 1,
    "Leader": "Lu Fuming",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 4,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Hubei",
    "Total amount received": 384,
    "Total giving amount": 348,
    "Philanthropists": 6,
    "Leader": "Wu Shaoxun",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 26,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 312,
    "Hunan": 10,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Hunan",
    "Total amount received": 155,
    "Total giving amount": 100,
    "Philanthropists": 1,
    "Leader": "Zhang Jingruo",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 100,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Jiangsu",
    "Total amount received": 22.3,
    "Total giving amount": 98.3,
    "Philanthropists": 8,
    "Leader": "Zhou Xijian",
    "Beijing": 64,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 1,
    "Jiangsu": 18.3,
    "Jiangxi": 5,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 10,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Jiangxi",
    "Total amount received": 5,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Jilin",
    "Total amount received": 310,
    "Total giving amount": 310,
    "Philanthropists": 1,
    "Leader": "Xing Fuping",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 310,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Liaoning",
    "Total amount received": 45.5,
    "Total giving amount": 38,
    "Philanthropists": 2,
    "Leader": "Sun Yinhuan",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 35,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 3,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Multiple Locations",
    "Total amount received": 4.5,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Nepal",
    "Total amount received": 11,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Ningxia",
    "Total amount received": 50.72,
    "Total giving amount": 50.72,
    "Philanthropists": 1,
    "Leader": "Dang Yanbao",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 50.72,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Shaanxi",
    "Total amount received": 11,
    "Total giving amount": 10,
    "Philanthropists": 1,
    "Leader": "Feng Xijian",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 10,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Shandong",
    "Total amount received": 11.5,
    "Total giving amount": 10,
    "Philanthropists": 1,
    "Leader": "Zhang Shiping",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 10,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Shanghai",
    "Total amount received": 305.9,
    "Total giving amount": 180,
    "Philanthropists": 3,
    "Leader": "Guo Guangchang",
    "Beijing": 60,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 120,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Shanxi",
    "Total amount received": 10,
    "Total giving amount": 10,
    "Philanthropists": 1,
    "Leader": "Li Guangzhong",
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 10,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Sichuan",
    "Total amount received": 139.5,
    "Total giving amount": 400,
    "Philanthropists": 6,
    "Leader": "Tang Lixin",
    "Beijing": 20,
    "Chongqing": 330,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 15,
    "Shanxi": 0,
    "Sichuan": 35,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Tianjin",
    "Total amount received": 251.9,
    "Total giving amount": 215.1,
    "Philanthropists": 5,
    "Leader": "Li Defu",
    "Beijing": 50,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 3,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0.5,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 160.6,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 1,
    "Zhejiang": 0
  },
  {
    "Province": "Tibet",
    "Total amount received": 2,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "US",
    "Total amount received": 62,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Xinjiang",
    "Total amount received": 0.6,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Yunnan",
    "Total amount received": 22.8,
    "Total giving amount": 0,
    "Philanthropists": 0,
    "Leader": 0,
    "Beijing": 0,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 0,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 0,
    "Shandong": 0,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 0,
    "Tianjin": 0,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 0,
    "Zhejiang": 0
  },
  {
    "Province": "Zhejiang",
    "Total amount received": 342.45,
    "Total giving amount": 370.05,
    "Philanthropists": 11,
    "Leader": "Wang Miaotong",
    "Beijing": 16,
    "Chongqing": 0,
    "Fujian": 0,
    "Gansu": 0,
    "Guangdong": 0,
    "Guangxi": 0,
    "Guizhou": 0,
    "Hebei": 0,
    "Heilongjiang": 0,
    "Henan": 0,
    "Hubei": 0,
    "Hunan": 0,
    "Jiangsu": 0,
    "Jiangxi": 0,
    "Jilin": 0,
    "Liaoning": 0,
    "Multiple Locations": 4.5,
    "Nepal": 0,
    "Ningxia": 0,
    "Shaanxi": 1,
    "Shandong": 1.5,
    "Shanghai": 0,
    "Shanxi": 0,
    "Sichuan": 1.5,
    "Tianjin": 11.3,
    "Tibet": 0,
    "US": 0,
    "Xinjiang": 0,
    "Yunnan": 1.8,
    "Zhejiang": 332.45
  }
];

    return map_chart_data;
}


function region_location(){

    var regions = [
        {
            "Province": "Anhui",
            "Province CN": "安徽",
            "Latitude": 475.5,
            "Longitude": 307.5
        },
        {
            "Province": "Beijing",
            "Province CN": "北京",
            "Latitude": 455.5,
            "Longitude": 190.5
        },
        {
            "Province": "Chongqing",
            "Province CN": "重庆",
            "Latitude": 360.5,
            "Longitude": 340.5
        },
        {
            "Province": "Fujian",
            "Province CN": "福建",
            "Latitude": 496.5,
            "Longitude": 398.5
        },
        {
            "Province": "Sichuan",
            "Province CN": "四川",
            "Latitude": 300.5,
            "Longitude": 330.5
        },
        {
            "Province": "Gansu",
            "Province CN": "甘肃",
            "Latitude": 325.5,
            "Longitude": 260.5
        },
        {
            "Province": "Qinghai",
            "Province CN": "青海",
            "Latitude": 235.5,
            "Longitude": 245.5
        },
        {
            "Province": "Tibet",
            "Province CN": "西藏",
            "Latitude": 150.5,
            "Longitude": 305.5
        },
        {
            "Province": "Xinjiang",     
            "Province CN": "新疆",       
            "Latitude": 122.5,
            "Longitude": 167.5
        },
        {
            "Province": "Yunnan",            
            "Province CN": "云南",
            "Latitude": 280.5,
            "Longitude": 415.5
        },
        {
            "Province": "Guangxi",      
            "Province CN": "广西",      
            "Latitude": 370.5,
            "Longitude": 425.5
        },
        {
            "Province": "Guangdong",  
            "Province CN": "广东",          
            "Latitude": 435.5,
            "Longitude": 450.5
        },
        {
            "Province": "Guizhou",     
            "Province CN": "贵州",       
            "Latitude": 350.5,
            "Longitude": 385.5
        },
        {
            "Province": "Hainan",  
            "Province CN": "海南",          
            "Latitude": 385.5,
            "Longitude": 495.5
        },
        {
            "Province": "Hunan",   
            "Province CN": "湖南",         
            "Latitude": 410.5,
            "Longitude": 375.5
        },
        {
            "Province": "Jiangxi",  
            "Province CN": "江西",          
            "Latitude": 455.5,
            "Longitude": 375.5
        },
        {
            "Province": "Taiwan",
            "Province CN": "台湾",            
            "Latitude": 530.5,
            "Longitude": 415.5
        },
        {
            "Province": "Zhejiang",
            "Province CN": "浙江",            
            "Latitude": 520.5,
            "Longitude": 341.5
        },
        {
            "Province": "Shanghai",    
            "Province CN": "上海",        
            "Latitude": 524.5,
            "Longitude": 315.5
        },
        {
            "Province": "Jiangsu",  
            "Province CN": "江苏",          
            "Latitude": 510.5,
            "Longitude": 285.5
        },
        {
            "Province": "Hubei",     
            "Province CN": "湖北",       
            "Latitude": 410.5,
            "Longitude": 320.5
        },
        {
            "Province": "Henan",
            "Province CN": "河南",            
            "Latitude": 425.5,
            "Longitude": 280.5
        },
        {
            "Province": "Shaanxi",  
            "Province CN": "陕西",          
            "Latitude": 375.5,
            "Longitude": 280.5
        },
        {
            "Province": "Ningxia",  
            "Province CN": "宁夏",          
            "Latitude": 345.5,
            "Longitude": 235.5
        },
        {
            "Province": "Inner Mongolia",     
            "Province CN": "内蒙古",       
            "Latitude": 395.5,
            "Longitude": 175.5
        },
        {
            "Province": "Shanxi",    
            "Province CN": "山西",        
            "Latitude": 415.5,
            "Longitude": 235.5
        },
        {
            "Province": "Hebei",            
            "Province CN": "河北",
            "Latitude": 445.5,
            "Longitude": 225.5
        },
        {
            "Province": "Shandong",   
            "Province CN": "山东",         
            "Latitude": 485.5,
            "Longitude": 245.5
        },
        {
            "Province": "Tianjin",  
            "Province CN": "天津",          
            "Latitude": 470.5,
            "Longitude": 208.5
        },
        {
            "Province": "Liaoning",  
            "Province CN": "辽宁",          
            "Latitude": 520.5,
            "Longitude": 180.5
        },
        {
            "Province": "Jilin",   
            "Province CN": "吉林",         
            "Latitude": 560.5,
            "Longitude": 140.5
        },
        {
            "Province": "Heilongjiang",
            "Province CN": "黑龙江",            
            "Latitude": 560.5,
            "Longitude": 85.5
        },
        {
            "Province": "Nepal",
            "Province CN": "尼泊尔",            
            "Latitude": 0,
            "Longitude": 0
        },
        {
            "Province": "US",
            "Province CN": "美国",            
            "Latitude": 0,
            "Longitude": 0
        }
    ];

    return regions;
}